/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/obj/home.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.HOMEM.geometry} material={nodes.HOMEM.material} position={[-28.33, 82.09, 15.07]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} >
      <meshPhysicalMaterial
          color = "#FA2BFD"
          />     
        </mesh>
    </group>
  )
}

useGLTF.preload('/obj/home.gltf')
