/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/obj/logo.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.logo_db.geometry} material={nodes.logo_db.material} position={[-60.25, 56.35, -0.04]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} >
      <meshPhysicalMaterial
          color = "white"
          />     
        </mesh>
    </group>
  )
}

useGLTF.preload('/obj/logo.gltf')
