/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/obj/casa.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Base.geometry} material={nodes.Base.material} position={[-229.22, 132.17, 124.06]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} >
        <meshPhysicalMaterial
          color = "#383DA5"
          />     
        </mesh>
    </group>
  )
}

useGLTF.preload('/obj/casa.gltf')
