/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/obj/laptop.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.19, 0.03, 0]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.Lowpoly_Body} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Lowpoly_Screen} />
      </group>
    </group>
  )
}

useGLTF.preload('/obj/laptop.gltf')
