/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/obj/mesa.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.mesa.geometry} material={nodes.mesa.material} position={[-101.33, -24.54, -32.33]} rotation={[Math.PI / 2, 0, 0]} scale={0.1} >
        <meshPhysicalMaterial
        color = "#52442B"
        />     
       </mesh>
    </group>

  )
}

useGLTF.preload('/obj/mesa.gltf')
